### ISSUE TITLE
Feat: Add Dependabot for flutter dependency Updates

### ISSUE THREAD

**Issue by samarsajad** [Yashshukla11/ExamTime_android#111]
### Describe the feature

I propose integrating Dependabot into our project to automate dependency updates. Dependabot will regularly check for updates, ensuring we stay current with the latest features and security patches. This will save time, enhance security, and maintain consistency in our development process.

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
@Yashshukla11 Please assign me this issue

**Comment by Shubham-Zone** [comment]
hey assing this to me i can do it

**Comment by Aakarsh-tech** [comment]
HI, Assing this work to me i can do it.
