### ISSUE TITLE
Feat: Notes like not reflecting in Likednotes page

### ISSUE THREAD

**Issue by Pra-kas** [Yashshukla11/ExamTime_android#113]
### Describe the feature

After a user likes a note, the note does not appear on the 'Liked Notes' page.

### Add ScreenShots

https://github.com/Yashshukla11/ExamTime_android/assets/103827847/343e69ca-7804-4eea-b1f1-0b88005b03a3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
hey @Yashshukla11  assign this to me i am GSSOC'24 contributor and have 2 years of experience in flutter
