### ISSUE TITLE
BUG:  Download Button Not Functioning on Real Devices

### ISSUE THREAD

**Issue by igopi77** [Yashshukla11/ExamTime_android#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description:**

There is an issue with the download button functionality in the ExamTime repository. When the download button is clicked, the file does not download on real devices.

**Steps to Reproduce:**

1. Open the ExamTime app on a real device.
2. Navigate to the section where the download button is available.
3. Click the download button.
4. Observe that the file does not download on the real device.

**Observed Behavior:**

- The file does not download on real devices when the download button is clicked.

**Expected Behavior:**

- The file should download successfully on real devices when the download button is clicked.

Possible Cause:

1. There might be an issue with the file path or storage permissions when the app is run on real devices.
2. Differences in how real devices handle file storage and permissions could be causing the issue.

**video sample**

https://github.com/Yashshukla11/ExamTime_android/assets/123234840/d43f5b9d-ea07-498e-bbc9-4c7754e74763

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Yashshukla11** [comment]
just reclone repo its working well
