### ISSUE TITLE
Missing Application Name

### ISSUE THREAD

**Issue by Rajkumarbhakta** [Yashshukla11/ExamTime_android#17]
<img alt="Screenshot" src="https://github.com/Yashshukla11/ExamTime_android/assets/85289204/b965630d-761e-4908-9082-0141ab95ee01" width="250"/>

**Comment by Rajkumarbhakta** [comment]
Hello I'm a contributor of GSSoC'2024 . I can fix this issue please assign me.

**Comment by dev04sa** [comment]
@Yashshukla11  , I'm a contributor of GSSoC'2024 . can you please assign this issue to me . I want to work on it

**Comment by AnanyaSinghal23** [comment]
I would like to work on this issue, please assign it to me. Thank you.
