### ISSUE TITLE
It asking login every time I open the application .

### ISSUE THREAD

**Issue by Rajkumarbhakta** [Yashshukla11/ExamTime_android#19]
https://github.com/Yashshukla11/ExamTime_android/assets/85289204/4a88b12e-3780-4fa2-bd8f-5cffccaa69bd

**Comment by Rajkumarbhakta** [comment]
I can work on this .Please assign me.

**Comment by Krishnabhattacharya** [comment]
I will fix this please assign me .

**Comment by Shruti78** [comment]
I am contributer of GSSOC'24 can u please assign me this issue.

**Comment by LEARNER-dakshesh** [comment]
Hey @Yashshukla11  can you please asssign me this issue . I can work on this
