### ISSUE TITLE
Feature Request : Add Share Option for Notes

### ISSUE THREAD

**Issue by igopi77** [Yashshukla11/ExamTime_android#27]
I propose enhancing the ExamTime app by adding a "Share" option for notes. This enhancement will simplify the sharing of study materials among others, promoting collaborative study and increasing user interaction.

**Key Points:**

1. **Share Functionality:** Implement a "_Share_" button within the notes interface, allowing users to quickly share specific notes with others.
2. **Multiple Sharing Options:** Provide options to share notes via popular platforms such as WhatsApp, email, and other social media platforms.

I believe implementing this feature would greatly benefit ExamTime users and contribute to a more robust and collaborative learning environment.

**Comment by AnanyaSinghal23** [comment]
I would like to work on this issue, please assign it to me. Thank you.

**Comment by Shruti78** [comment]
I would like to work on this issue, assign it to me.

**Comment by igopi77** [comment]
Hello @Yashshukla11 please assign this work to me.

**Comment by Shubham-Zone** [comment]
I would like to work on this issue, please assign it to me. Thank you.

**Comment by igopi77** [comment]
https://github.com/Yashshukla11/ExamTime_android/assets/123234840/b860efbb-8130-41f0-8961-56d975db792a

Hi @Yashshukla11 sir. I have been completed this feature. Please review it. 
Can I raise a PR?

**Comment by igopi77** [comment]
Hii @Yashshukla11 sir, PR raised.

**Comment by Yashshukla11** [comment]
> Hii @Yashshukla11 sir, PR raised.

merger, good work👍

**Comment by igopi77** [comment]
Thankyou sir @Yashshukla11. You can close this issue.
