### ISSUE TITLE
BUG: Two app files cant be contained in one project 

### ISSUE THREAD

**Issue by Bhavneet-singh** [Yashshukla11/ExamTime_android#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Yashshukla11/ExamTime_android/assets/109847685/f653dcfe-7045-4ee0-938c-b21fc54e4c8b)
![image](https://github.com/Yashshukla11/ExamTime_android/assets/109847685/69ce5322-e6fa-44f0-8c62-66497fc416e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by karthickkumarsm** [comment]
let me help with this
