### ISSUE TITLE
Doc: Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Yashshukla11/ExamTime_android#57]
### Describe the documentation update needed

I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

### Reason for Update

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

### Proposed Changes

I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Yashshukla11** [comment]
@PradnyaGaitonde can you kindly explain what exactly you want to do.

**Comment by PradnyaGaitonde** [comment]
@Yashshukla11 I want to add instructions for contributors on how to contribute using GitHub Desktop, as these are not currently included in the contributing file. Since GitHub Desktop is widely used, this addition will help and encourage more contributors to work efficiently. Could you please assign this to me under gssoc24?
