### ISSUE TITLE
Feat: Eye Button Functionality Inconsistent Between Password and Confirm Password Fields

### ISSUE THREAD

**Issue by VIDHIGUPTA17** [Yashshukla11/ExamTime_android#65]
### Describe the feature

Problem Description:

Users have reported an inconsistency in the functionality of the eye button (often used for toggling password visibility) between the "Password" and "Confirm Password" fields during both the login and registration processes.

Steps to Reproduce:

Navigate to the login or registration page.
Observe the presence of an eye button/icon next to the "Password" and "Confirm Password" fields.
Click on the eye button next to the "Password" field to toggle password visibility.
Attempt to click on the eye button next to the "Confirm Password" field.
Expected Behavior:

The eye button next to the "Password" field should toggle password visibility, allowing users to view or hide their entered password for increased convenience and security.
The eye button next to the "Confirm Password" field should exhibit similar functionality, enabling users to toggle visibility of their confirmed password during registration.
Actual Behavior:

While the eye button next to the "Password" field functions as expected, providing users with the option to toggle password visibility, the eye button next to the "Confirm Password" field does not respond to user interaction. This lack of functionality prevents users from conveniently verifying the accuracy of their entered passwords during registration.

Additional Context:

Consistent and intuitive user interfaces contribute to a positive user experience and reduce user confusion. Implementing consistent functionality for the eye button across all password input fields ensures uniformity and ease of use. Additionally, providing users with the ability to verify their confirmed password enhances usability and reduces input errors during the registration process.

### Add ScreenShots

![1_n15qxWxVfhAQTD7AGb9Klg](https://github.com/Yashshukla11/ExamTime_android/assets/115092172/610dc3ae-3383-4b59-80d7-91f2bd99b83f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by SumitPareek2401** [comment]
@Yashshukla11 Please assign this issue to me so that other contributors can also have a chance to contribute.

**Comment by nishant0708** [comment]
Hello , I'm interested in contributing to the project by implementing Support Us functionality. Could you please assign this task to me under GSSoC'24 with appropriate level?

**Comment by LEARNER-dakshesh** [comment]
Hey @Yashshukla11  can you please asssign me this issue . I can work on this.
