### ISSUE TITLE
BUG: Add a page for otp verification 

### ISSUE THREAD

**Issue by Yashshukla11** [Yashshukla11/ExamTime_android#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

none

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by MohitShukla29** [comment]
@Yashshukla11  kindly assign me this issue. I want to work on it.

**Comment by pavants777** [comment]
@Yashshukla11 assign me too, I will also work for this...
