### ISSUE TITLE
Integrating the backend for otp verification

### ISSUE THREAD

**Issue by MohitShukla29** [Yashshukla11/ExamTime_android#73]
### Describe the feature

Backend integration to verify the otp

### Add ScreenShots

Null

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by LEARNER-dakshesh** [comment]
Hey @Yashshukla11  can you please asssign me this issue . I can work on this .
