### ISSUE TITLE
BUG:Feat:  fucntionality of share and like is need to improve

### ISSUE THREAD

**Issue by Subhash23jan** [Yashshukla11/ExamTime_android#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

user can share their notes and have liked notes list and i would like to enhance  this feature 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Yashshukla11** [comment]
@Subhash23jan what's the status .

**Comment by Subhash23jan** [comment]
![Screenshot_2024-05-18-08-35-07-829_com android chrome](https://github.com/Yashshukla11/ExamTime_android/assets/117830405/0788512e-2198-4d45-ba7a-99ec1e5dfc59)
I already rised PR for both the issues
