### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [Yashshukla11/ExamTime_android#85]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by suhanipaliwal** [comment]
Please add the labels of gssoc and appropriate level like level1 , level2 or level3 on this issue.

**Comment by prajapatihet** [comment]
Is this Issue still open?

**Comment by Yashshukla11** [comment]
no
