### ISSUE TITLE
The emails are not checked and any wrong value can be filled in those forms.

### ISSUE THREAD

**Issue by a-m-a-nkumar** [Yashshukla11/ExamTime_android#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a person enters an incorrect mobile number (not a 10-digit number), it should be identified and reported to the user. Additionally, if the user enters an easy password, they should be notified to enter a stronger password. Email and password fields can be filled with any values without being checked.

https://github.com/Yashshukla11/ExamTime_android/assets/99753046/020dc821-26ef-4e1e-95c9-9beca56ec188

https://github.com/Yashshukla11/ExamTime_android/assets/99753046/8ed1fd5a-2d43-4752-828c-d2d5155eed05

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Shruti78** [comment]
Kindly assign me this issue i will solve it.
